project:
  type: book
  output-dir: docs

book:
  title: "Cayley Graph Intro"
  author: "mobmob"
  date: "6/15/2025"
  cover-image: https://placehold.co/600x800?text=Cayley+Graph+Intro
  chapters:
    - index.qmd
    - intro.qmd
    - basics.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand



